### ISSUE TITLE
Performance boost (making initialization faster)

### ISSUE THREAD

**Issue by henhok** [sivanni/CXSystem_Git#2]
Basic flow of things: Generating neuron groups -> generating synapses -> Initializing the simulation -> running the simulation. How can we make the first 3 parts run faster?

**Comment by Vafa-Andalibi** [comment]
This issue is now closed since the CxSystem now works with the latest brian2 release that supports weave code generation for python that makes the initialisation much faster. C++ and GeNN standalone devices are already fast at initialisation.
