### ISSUE TITLE
refactor SNS_name to something meaningful

### ISSUE THREAD

**Issue by sivanni** [sivanni/CXSystem_Git#35]
consider also S_name to become synapse_name (if it is so?). Mapping from "S0_Fixed" etc to connection btw named cell groups would be a useful map, too. You could eg comment which variable houses this mapping.

**Comment by Vafa-Andalibi** [comment]
Fixed, several variable names related to neurons and synapses are now self-descriptive. S0_Fixed is also changed to S0_Fixed_NG1_PC_L4toL2__to__NG2_PC_L2toL1 (example)
