### ISSUE TITLE
Repeated runs

### ISSUE THREAD

**Issue by sivanni** [sivanni/CXSystem_Git#36]
If run is repeated with same params, eg by using {0.3&0.3&0.3&0.3&0.3&0.3&0.3&0.3}, they are all run, but only one of them is listed in the metadata, and thus visualized . See Pikkuveli /opt/Laskenta/Output/for_vafa_debug to see the files- 

The final metadata was "touch ..." ed to see whether this was a problem of not being most recent time stamp. Thus the different most recent acces times.

**Comment by sivanni** [comment]
One option would be to add parameter "iterate_each_run" (integer), and run each param combination with that N times

**Comment by Vafa-Andalibi** [comment]
This options is already implemented (use trials_per_config in anatomy/network config file)
